/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Cta = {
	_type: 'cta';
	heading: string;
	lead?: string;
	button: LabeledLink;
};

export type Gallery = {
	_type: 'gallery';
	heading?: string;
	images: Array<
		{
			_key: string;
		} & ImageWithAlt
	>;
};

export type Faq = {
	_type: 'faq';
	heading?: string;
	items: Array<{
		question: string;
		answer: RichText;
		_type: 'faqItem';
		_key: string;
	}>;
};

export type Testimonials = {
	_type: 'testimonials';
	heading?: string;
	items: Array<{
		quote: string;
		author: string;
		role?: string;
		avatar?: ImageWithAlt;
		_type: 'testimonial';
		_key: string;
	}>;
};

export type Pricing = {
	_type: 'pricing';
	heading?: string;
	lead?: string;
	plans: Array<{
		name: string;
		price: string;
		unit?: string;
		description?: string;
		includes?: Array<string>;
		button?: LabeledLink;
		recommended?: boolean;
		_type: 'plan';
		_key: string;
	}>;
};

export type Features = {
	_type: 'features';
	heading?: string;
	lead?: string;
	items: Array<{
		title: string;
		description?: string;
		_type: 'feature';
		_key: string;
	}>;
};

export type TextImage = {
	_type: 'textImage';
	heading: string;
	body?: RichText;
	image: ImageWithAlt;
	imagePosition?: 'right' | 'left';
};

export type Hero = {
	_type: 'hero';
	heading: string;
	lead?: string;
	image?: ImageWithAlt;
	buttons?: Array<
		{
			_key: string;
		} & LabeledLink
	>;
};

export type LabeledLink = {
	_type: 'labeledLink';
	label: string;
	link: Link;
};

export type PageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'page';
};

export type Link = {
	_type: 'link';
	kind: 'internal' | 'external';
	page?: PageReference;
	href?: string;
	newTab?: boolean;
};

export type RichText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'h2' | 'h3';
	listItem?: 'bullet' | 'number';
	markDefs?: Array<
		{
			_key: string;
		} & Link
	>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
	_type: 'imageWithAlt';
	asset?: SanityImageAssetReference;
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt?: string;
};

export type Seo = {
	_type: 'seo';
	metaTitle: string;
	metaDescription: string;
	ogImage?: ImageWithAlt;
	noindex?: boolean;
};

export type Redirect = {
	_id: string;
	_type: 'redirect';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	from: string;
	to: string;
	permanent?: boolean;
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	sections: Array<
		| ({
				_key: string;
		  } & Hero)
		| ({
				_key: string;
		  } & TextImage)
		| ({
				_key: string;
		  } & Features)
		| ({
				_key: string;
		  } & Pricing)
		| ({
				_key: string;
		  } & Testimonials)
		| ({
				_key: string;
		  } & Faq)
		| ({
				_key: string;
		  } & Gallery)
		| ({
				_key: string;
		  } & Cta)
	>;
	seo: Seo;
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type Navigation = {
	_id: string;
	_type: 'navigation';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	mainMenu?: Array<
		{
			_key: string;
		} & LabeledLink
	>;
	footerMenu?: Array<
		{
			_key: string;
		} & LabeledLink
	>;
};

export type SiteSettings = {
	_id: string;
	_type: 'siteSettings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	companyName: string;
	tagline?: string;
	nip?: string;
	address?: {
		street: string;
		postalCode: string;
		city: string;
		country: string;
	};
	phone: string;
	email: string;
	openingHours?: Array<{
		days: Array<string>;
		closed?: boolean;
		opens?: string;
		closes?: string;
		_type: 'openingHoursEntry';
		_key: string;
	}>;
	social?: Array<{
		platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'x';
		url: string;
		_type: 'socialProfile';
		_key: string;
	}>;
	logo?: ImageWithAlt;
	defaultOgImage?: ImageWithAlt;
	analytics?: {
		provider?: 'none' | 'plausible' | 'umami';
		domain?: string;
		scriptHost?: string;
	};
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x: number;
	y: number;
	height: number;
	width: number;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| Cta
	| Gallery
	| Faq
	| Testimonials
	| Pricing
	| Features
	| TextImage
	| Hero
	| LabeledLink
	| PageReference
	| Link
	| RichText
	| SanityImageAssetReference
	| ImageWithAlt
	| Seo
	| Redirect
	| Page
	| Slug
	| Navigation
	| SiteSettings
	| SanityImageCrop
	| SanityImageHotspot
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
